apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
      - name: dev-container
        image: 'us-central1-docker.pkg.dev/gcr.io/qwiklabs-gcp-04-3ed1c022ed3c/my-repository/hello-cloudbuild-dev:v1.0'
        ports:
        - containerPort: 8080
