apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
      - name: dev-container
        image: gcr.io/qwiklabs-gcp-04-3ed1c022ed3c/sample-app:v1.0|g" sample-app/dev/deployment.yaml
        ports:
        - containerPort: 8080
